main:
  - name: Introduce
    url: /author/Yun_Hanseo
    weight: 10

  - name: Projects
    url: /myproject/
    weight: 20
  - parent: Projects
    name: Quantum computer
    url: /myproject/projectquantum
    weight: 21
  - parent: Projects
    name: Linux Account Withdrawal
    url: /myproject/projectlinux
    weight: 22
  - parent: Projects
    name: Creating a Homepage
    url: /myproject/projecthomepage/
    weight: 23

  - name: Interest
    url: /intrest/
    weight: 30
  - parent: Interest
    name: AI
    url: /interest/interest1_ai
    weight: 31
  - parent: Interest
    name: Game Development
    url: /interest/interest2_gamedevelop
    weight: 32
  - parent: Interest
    name: Aerospace
    url : /interest/interest3_aerospace
    weight: 33

  - name: Hobbies
    url: /like/
    weight: 40
  - parent: Hobbies
    name: Reading
    url: /like/read/
    weight: 41
  - parent: Hobbies
    name: Photography
    url: /like/picture/
    weight: 42
  - parent: Hobbies
    name: Drawing
    url: /like/drawing/
    weight: 43

  - name: Contact
    url: contact
    weight: 50