main:
  - name: Introduce
    url: /author/Yun_Hanseo
    weight: 10

  - name: Projects
    url: /myproject/
    weight: 20
  - parent: Projects
    name: Quantum computer
    url: /myproject/projectquantum
    weight: 30
  - parent: Projects
    name: Linux Account Withdrawal
    url: /myproject/projectlinux
    weight: 40
  - parent: Projects
    name: Creating a Homepage
    url: /myproject/projecthomepage/
    weight: 50

  - name: Interest
    url: /intrest/
    weight: 60
  - parent: Interest
    name: AI
    url: /interest/interest1_ai
    weight: 70
  - parent: Interest
    name: Game Development
    url: /interest/interest2_gamedevelop
    weight: 80
  - parent: Interest
    name: Aerospace
    url : /interest/interest3_aerospace
    weight: 90

  - name: 취미
    url: /like/
    weight: 100
  - parent: 취미
    name: 독서
    url: /like/read/
    weight: 110
  - parent: 취미
    name: 사진
    url: /like/picture/
    weight: 120
  - parent: 취미
    name: 그림
    url: /like/drawing/
    weight: 130

  - name: Contact
    url: contact
    weight: 140