# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /author/윤한서
    weight: 10

  - name: 프로젝트
    url: /myproject/
    weight: 20
  - parent: 프로젝트
    name: 양자역학컴퓨터
    url: /myproject/projectquantum
  - parent: 프로젝트
    name: 리눅스 계좌인출
    url: /myproject/projectlinux
  - parent: 프로젝트
    name: 홈페이지 만들기
    url: /myproject/projecthomepage/

  - name: 관심분야
    url: /intrest/
    weight: 30
  - parent: 관심분야
    name: 인공지능
    url: /interest/interest1_ai
  - parent: 관심분야
    name: 항공우주
    url : /interest/interest2_aerospace
  - parent: 관심분야
    name: 게임개발
    url: /interest/interest3_gamedevelop

  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: 연락
    url: contact
    weight: 60
